---
name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up Python 3.11.4
          uses: actions/setup-python@v4
          with:
            python-version: 3.11.4
        - name: Install poetry
          run: pip3 install poetry==1.5.1
        - name: Install Python dependencies
          run: poetry install
        - name: Run Tests
          run: poetry run pytest test/
